import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar2 from "@/components/Navbar2";
import { AuthProvider } from "./context/AuthContext";
import { FollowProvider } from "./context/FollowContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <FollowProvider>
        <Navbar2 />
        <main className="relative overflow-hidden">{children}</main>
       
        </FollowProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
