import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar2 from "@/components/Navbar2";
import { AuthProvider } from "./context/AuthContext";
import { FollowProvider } from "./context/FollowContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <FollowProvider>
            <div className="flex md:flex-col min-h-screen flex-col-reverse">
              <Navbar2 className="md:order-first fixed top-0 left-0 right-0 z-50 bg-white shadow-md" />
              <main className="relative overflow-hidden flex-1">{children}</main>
            </div>
          </FollowProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
